name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: dutterbutter/foundry-zksync-toolchain@v1

      - name: Install deps
        run: forge soldeer install

      - name: Run anvil-zksync
        uses: dutterbutter/anvil-zksync-action@v1.1.0
        with:
          mode: run 
          logFilePath: anvil_zksync.log
          target: x86_64-unknown-linux-gnu
          releaseTag: latest

      - name: Run Forge script test
        run: |
          forge script script/Counter.s.sol --zksync --broadcast --private-key 0x8b3a350cf5c34c9194ca85829a2df0ec3153be0318b5e2d3348e872092edffba --rpc-url http://127.0.0.1:8011

      - name: Show Forge version
        run: |
          forge --version

      - name: Run Forge fmt
        run: |
          forge fmt --check
        id: fmt

      - name: Run Forge build
        run: |
          forge build --sizes --zksync
        id: build

      - name: Run Forge tests
        run: |
          forge test -vvv --zksync
        id: test


